### ISSUE TITLE
Having heuristics between models

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#114]
This can be a place holder for a longer discussion.
In a nutshell, if I'm using 2 different algorithms and I feed them into sklearn, it should be able to show me discrepancies between roc values for instance. The assignee should also explore for existing tools out there or samples that might help solve this challenge.

**Comment by edublancas** [comment]
this is similar to the second option I proposed [here](https://github.com/ploomber/sklearn-evaluation/issues/113#issuecomment-1364367315).

I'm thinking something like this:

```python
from sklearn_evaluation import compare_classifiers

compare_classifiers(random_forest, linear_regression)
```

`compare_classifiers` should display an HTML report with an analysis. I think before we implement this, we should do some research on what kind of heuristics make sense.

**Comment by idomic** [comment]
I think we should split this, one is internal (#113), the other is inter-model (#114)

**Comment by edublancas** [comment]
Adding a few more details here. We already have some basic [report](https://github.com/ploomber/sklearn-evaluation/tree/master/src/sklearn_evaluation/report) module that generates an HTML report using this [template](https://github.com/ploomber/sklearn-evaluation/blob/master/src/sklearn_evaluation/assets/report/classifier.md). However, it's too basic, it just adds a bunch of plots into an HTML file.

We propose two new functions (or classes?) to generate more comprehensive reports. We can start with classifiers since that's the most common use case.

## evaluating a single model

The first one is to evaluate a single model. For example, suppose I have a  random forest. In that case, I'd like to understand its performance without overthinking, "I need plot A to evaluate B and plot C to evaluate D." This function should be smart enough (via some hand-coded heuristics) to determine what the most relevant plots given my model/performance. Here's some API I'm thinking of:

```python
from sklearn_evaluation import evaluate_model

# y_true: actual labels in test set
# y_pred: predictions from random forest in test set
evaluate_model(y_true, y_pred, random_forest)
```

Then the report might some me different plots (along with some human-readable sentences) to interpret the results, examples:

- Your test set is highly imbalanced (then show the distribution of classes). To tackle this, check out this guide (link to our guide on tackling class imbalance)
- Your area under the curve  is low (then show ROC curve), To tackle this, check out this guide (link to tutorial on interpreting ROC curve and  how to improve are under the curve)

Note that we should make some arguments optional; depending on how many inputs we have, we'll have more room for more diagnostic information. These are the relevant pieces:

- X_train, y_train
- X_test, y_test/y_pred
- Model object

For example, if the user also passes the featurs:

```python
evaluate_model(y_true, y_pred, random_forest, X_train, X_test)
```

We can compute feature correlations to indicate the user whether some feature pruning can help improve performance.

## model comparison

The second function can compare two models:

```python
compare_models(model, another_model, X_train, X_test)
```

Then highlight differences and allow the user to make an informed decision on which one to use. Examples:

- Model A has more precision, model B has better recall
- Models have comparable area-under-the-curve
- Model A is a lot more computational expensive
- Model B is well-calibrated

Here we can use our combined plots to produce confusion matrices and other plots that compare both models.

## considerations

The tricky part here is defining the heuristics we'll use; coding will be the easy part.

**Comment by yafimvo** [comment]
@edublancas I think it looks good.
How many models are we eventually want to support?
Are these models require the same optional arguments?

If there are more models (let's say more than 2) with some unique optional arguments for each, it might be difficult to maintain and use.

In that case, we can do something like this

```python
from sklearn_evaluation import evaluate_model
from evaluate_model import RandomForest

# y_true: actual labels in test set
# y_pred: predictions from random forest in test set
rf_report = RandomForest(y_true, y_pred, X_train, X_test)
```

**Comment by edublancas** [comment]
> How many models are we eventually want to support?

I think let's start with evaluating one model and then comparing two models

> Are these models require the same optional arguments?

Good point. We can start by comparing aspects that do not depend on the model itself but on its predictions - since all models can generate predictions, we can treat them equally.

There are many open questions here so, let's start with the simplest use case: evaluate a single model.
