### ISSUE TITLE
confusion matrix plots are being cropped

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#145]
2 examples: https://sklearn-evaluation.ploomber.io/en/latest/classification/compare.html
and the quick start on binder (photos attached). The left side of the index is cut in the middle. We should probably adjust the ratio of the plot.

<img width="538" alt="Screen Shot 2022-12-27 at 12 22 27 PM" src="https://user-images.githubusercontent.com/11596985/209700730-d0ee3a00-be59-4fb8-942b-3bb1bf3cbd77.png">
<img width="655" alt="Screen Shot 2022-12-27 at 12 23 09 PM" src="https://user-images.githubusercontent.com/11596985/209700733-3cfdaf55-e165-42fe-9f3a-e999b83d4dd4.png">

**Comment by neelasha23** [comment]
`figsize` parameter might help.

**Comment by idomic** [comment]
@neelasha23 want to take this?
Should be pretty straight forward

**Comment by edublancas** [comment]
I don't think we should use `figsize` since that will hardcode the size of the figure and users might wanna tweak it. The cropped plots are a consequence of how I implemented the combined plot: I'm serializing the plot as `base64` and then displaying it using `IPython.display.HTML`.

That was the quickest solution but it's not the best long-term. The best solution is to keep using matplotlib objects so the user can customize the sizes. We can follow a similar model as sklearn: https://github.com/scikit-learn/scikit-learn/blob/98cf537f5/sklearn/metrics/_plot/roc_curve.py#L10

**Comment by edublancas** [comment]
essentially what we want is the class methods to call an internal `.plot()` method that creates and displays the plot

**Comment by neelasha23** [comment]
Yes I can take it up @idomic

**Comment by edublancas** [comment]
hey, I started doing the `.plot()` refactoring in ConfusionMatrix. This will fix this issue as a side-effect. I'll open a few more issues since we need to migrate other plots to the object-oriented API

**Comment by edublancas** [comment]
we discussed and agreed on this. this is is related to my earlier comment:

> I don't think we should use figsize since that will hardcode the size of the figure and users might wanna tweak it. The cropped plots are a consequence of how I implemented the combined plot: I'm serializing the plot as base64 and then displaying it using IPython.display.HTML.

> That was the quickest solution but it's not the best long-term. The best solution is to keep using matplotlib objects so the user can customize the sizes. We can follow a similar model as sklearn: https://github.com/scikit-learn/scikit-learn/blob/98cf537f5/sklearn/metrics/_plot/roc_curve.py#L10

there is no impact to end-users
