### ISSUE TITLE
Document heteroscedasticity in regression

### ISSUE THREAD

**Issue by neelasha23** [ploomber/sklearn-evaluation#166]
Document the problem of heteroscedasticity in regression using residual plots, and approaches of solving it.

**Comment by edublancas** [comment]
good point, this can be part of our regression user guide. and then link from the docstring to that section

**Comment by BaturalpOzturk** [comment]
Important issue that can be easily unrecked.

**Comment by edublancas** [comment]
the file to modify is this: https://github.com/ploomber/sklearn-evaluation/tree/master/docs/regression

**Comment by TegveerG** [comment]
Acknowledging assignment.

**Comment by TegveerG** [comment]
Hi @edublancas I have a template ready that I plan to include in the RegressionPlots.md doc. I also have a few questions in context of this template I have created. This is the flow of the doc after the Cook's Distance section:

## Heteroscedasticity in Regression

+++

### Detecting Heteroscedasticity

+++

```{code-cell} ipython3

```

#### Breusch-Pagan Test (from statsmodels)

+++

```{code-cell} ipython3

```

#### Goldfeld-Quandt Test (from statsmodels)

+++

```{code-cell} ipython3

```

### Problems Caused by Heteroscedasticity

+++

### Transformations to Fix Heteroscedasticity

+++

#### Variable Transformations and Polynomials

+++

```{code-cell} ipython3

```

The first question I had is regarding the use of the statsmodels package for the Breusch-Pagan Test and Goldfeld-Quandt Test. Although we are creating a tutorial for sklearn, would you still be open to importing and using a different library for this issue? 
The second clarification is regarding graphical visualizations. Although the markdown provides code to produce plots for Residuals and Cook's Distance, I am thinking of including inline visualizations of the diabetes dataset for better explainability. If this is not feasible, please let me know and I shall only include code for generating plots.

I shall push my first commit once I obtain your reply. Thank you!

**Comment by edublancas** [comment]
>  The first question I had is regarding the use of the statsmodels package for the Breusch-Pagan Test and Goldfeld-Quandt Test. Although we are creating a tutorial for sklearn, would you still be open to importing and using a different library, including numpy, for this issue?

Sure, we can use numpy and statsmodels

> The second clarification is regarding graphical visualizations. Although the markdown provides code to produce plots for Residuals and Cook's Distance, I am thinking of including inline visualizations of the diabetes dataset for better explainability. If this is not feasible, please let me know and I shall only include code for generating plots.

You can write the tutorial from Jupyter, once you push it, our doc building system runs the notebook and it'll publish it with all the required plots, so there's no need to manually upload images. More info here: https://github.com/ploomber/contributing/blob/main/documentation/notebooks.md

**Comment by TegveerG** [comment]
Alright thank you for the clarifications! I shall push a final commit by a tomorrow, this time with a jupyter notebook, updated with the Breusch-Pagan Test and Goldfeld-Quandt Test from statsmodels.

**Comment by TegveerG** [comment]
Hi @edublancas, I have created my Pull Request and the link for it is below:

https://github.com/ploomber/sklearn-evaluation/pull/308

I had a lot of fun with this deliverable and it was interesting to work using the Ploomber way! Please let me know if you have any questions or comments and we can reconvene at your convenience.
