### ISSUE TITLE
Making sure our docs are SEO optimized

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#253]
https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html

**Comment by yafimvo** [comment]
I went over the doc and ran SEO tests on our docs and compared it with some other similar docs. I took the `jupysql` docs as an example.

According to this article, we are OK. Our `robots.txt` and `sitemap.xml` are in place and everything is linked. butm there is a place for improvement. Unfortunately, since we're using an auto doc builder like jupyter-book, I'm not sure it's that easy though (e.g: our links and headers are generated automatically).

### Our score
![image](https://user-images.githubusercontent.com/103026689/219012147-48de2a21-608b-4f65-a3d4-e7a46fdf3345.png)


### Jupyter-book score
![image](https://user-images.githubusercontent.com/103026689/219012224-ed8ab420-bafa-45ea-976a-bf9e7661a7af.png)


### Sphinx docs
![image](https://user-images.githubusercontent.com/103026689/219012286-72375269-5fb5-4c79-a6f6-dfd736abaeb9.png)

## Solution
I think the easiest and most effective thing we can start with is adding metadata tags to our docs.

### Add `RestructuredText` to `rst` files

```md
.. meta::
    :description lang=en:
        A brief explanation of the content and purpose of this page
```

### Add `html_meta` to every `md` files

```md
---
jupytext:
  formats: md:myst
  text_representation:
    extension: .md
    format_name: myst
    format_version: 0.13
    jupytext_version: 1.14.4
kernelspec:
  display_name: Python 3 (ipykernel)
  language: python
  name: python3
html_meta:
  "description lang=en": "Some description"
  "keywords": "Key1, Key2"
  "property=og:locale": "en_US"  
---
```

@edublancas @idomic 
We need to decide which tags to use and how to describe every article.

**Comment by edublancas** [comment]
is there a way to add keywords to rst files?

---

I opened issues to track adding the metadata:

https://github.com/ploomber/jupysql/issues/132
https://github.com/ploomber/sklearn-evaluation/issues/290
https://github.com/ploomber/ploomber-engine/issues/48

but let's keep this open so we revisit our SEO scores once those are in

**Comment by yafimvo** [comment]
> is there a way to add keywords to rst files?

yes.

```
.. meta::
    :description lang=en:
        Some description
    :keywords: Tag1, Tag2
```

**Comment by edublancas** [comment]
To add metadata to a notebook:

```json
    "html_meta": {
        "description lang=en": "Description",
        "keywords": "Key1, Key2",
        "property=og:locale": "en_US"
    }
```

![Screenshot 2023-03-03 at 6 30 12 p m](https://user-images.githubusercontent.com/989250/222860519-485d1015-fb1e-48d6-ae13-484ef0be471b.png)
