### ISSUE TITLE
This binder example fails

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#49]
https://sklearn-evaluation.readthedocs.io/en/latest/user_guide/compare.html

**Comment by edublancas** [comment]
I fixed it. The problem is that binder caches the conda environment in a Docker image; hence, when we add a new feature like that, it won't work because it'd still use an old version of the package.

So we need a way to update the binder environment automatically. I think there is an open issue already so I'll close this one and tag you on the other one to discuss a solution.
