### ISSUE TITLE
Overlapping plots

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#99]
When trying to print multiple plots via the same cell, the matrix and feature importance are overlapping.

i.e:
```
KNN = KNeighborsClassifier()
KNN.fit(X_train, y_train)
predictions= KNN.predict(X_test)
print(accuracy_score(y_test, predictions))
print(classification_report(y_test, predictions))
knn_cm = plot.confusion_matrix(y_test, predictions)
plot.feature_importances(rfc, top_n=5)
```
<img width="857" alt="Screen Shot 2022-12-21 at 3 24 33 PM" src="https://user-images.githubusercontent.com/11596985/208996698-9a727494-e549-438a-94c9-735a0f0c2a72.png">

**Comment by edublancas** [comment]
Ah, this problem goes back a while due to an error I made when creating the first plots.

Our plotting methods have a `ax` argument that allows you to use a matplotlib.Axes object and add your plot there. The typical use case is someone plotting 4 plots in a 2 x 2 grid, and then passing the Axes objects to the plotting methods to fill the grid.

However, when a user does not pass the `ax` argument, we [set a default](https://github.com/ploomber/sklearn-evaluation/search?q=plt.gca%28%29), currently, we're setting it as:

```python
ax = plt.gca()
```

This means "get current axes". The problem with this approach is that it'll re-use the same axes (that's why the plots overlap). I'm unsure what's matplotlib's rule for deciding when to create a new Axes object. Maybe if running it in a different cell will force creating a new axes?

I think what's best is to do:

```python
_, ax = plt.subplots()
```

just like [sklearn](https://github.com/scikit-learn/scikit-learn/blob/98cf537f5c538fdbc9d27b851cf03ce7611b8a48/sklearn/metrics/_plot/roc_curve.py#L124) does 


This will create a new axes object. I don't think this will have any impact for end-users, but once we make the change, we can check the rendered docs and examples to see if anything looks odd.

**Comment by edublancas** [comment]
note: I fixed this for confusion matrix, this PR can be used as reference: https://github.com/ploomber/sklearn-evaluation/pull/208

**Comment by WSShawn** [comment]
okay! I'll check it out!

**Comment by edublancas** [comment]
this has been fixed https://github.com/ploomber/sklearn-evaluation/pull/211

**Comment by idomic** [comment]
Is there anything else or we cna close this?

**Comment by edublancas** [comment]
nothing else to do, we can close it
